"""convert all timestamp columns to TIMESTAMP WITH TIME ZONE

All datetime values stored so far were generated by datetime.now(timezone.utc)
and are therefore UTC.  The USING … AT TIME ZONE 'UTC' clause tells PostgreSQL
to reinterpret each stored naive value as UTC before converting it to a
timestamptz — no data is lost or shifted.

Revision ID: c4e1f9a03b72
Revises: ed6aa6c2270c
Create Date: 2026-05-27

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c4e1f9a03b72"
down_revision: Union[str, Sequence[str], None] = "ed6aa6c2270c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

_NAIVE = sa.DateTime(timezone=False)
_TZ    = sa.DateTime(timezone=True)


def _to_timestamptz(table: str, column: str, *, nullable: bool = False) -> None:
    """ALTER one column from TIMESTAMP → TIMESTAMPTZ, reinterpreting as UTC."""
    op.alter_column(
        table,
        column,
        existing_type=_NAIVE,
        type_=_TZ,
        existing_nullable=nullable,
        postgresql_using=f"{column} AT TIME ZONE 'UTC'",
    )


def _to_timestamp(table: str, column: str, *, nullable: bool = False) -> None:
    """ALTER one column from TIMESTAMPTZ → TIMESTAMP, stripping the UTC offset."""
    op.alter_column(
        table,
        column,
        existing_type=_TZ,
        type_=_NAIVE,
        existing_nullable=nullable,
        postgresql_using=f"{column} AT TIME ZONE 'UTC'",
    )


# ---------------------------------------------------------------------------
# Upgrade: TIMESTAMP WITHOUT TIME ZONE → TIMESTAMP WITH TIME ZONE
# ---------------------------------------------------------------------------

def upgrade() -> None:
    # users
    _to_timestamptz("users", "created_at")

    # incidents
    _to_timestamptz("incidents", "resolved_at", nullable=True)
    _to_timestamptz("incidents", "created_at")
    _to_timestamptz("incidents", "updated_at")

    # fix_flows
    _to_timestamptz("fix_flows", "created_at")

    # checklist_items
    _to_timestamptz("checklist_items", "updated_at")

    # notes
    _to_timestamptz("notes", "updated_at")

    # timeline_events
    _to_timestamptz("timeline_events", "occurred_at")

    # similar_incidents
    _to_timestamptz("similar_incidents", "created_at")


# ---------------------------------------------------------------------------
# Downgrade: TIMESTAMP WITH TIME ZONE → TIMESTAMP WITHOUT TIME ZONE
# (values are converted back to plain UTC timestamps — no data loss)
# ---------------------------------------------------------------------------

def downgrade() -> None:
    # similar_incidents
    _to_timestamp("similar_incidents", "created_at")

    # timeline_events
    _to_timestamp("timeline_events", "occurred_at")

    # notes
    _to_timestamp("notes", "updated_at")

    # checklist_items
    _to_timestamp("checklist_items", "updated_at")

    # fix_flows
    _to_timestamp("fix_flows", "created_at")

    # incidents
    _to_timestamp("incidents", "updated_at")
    _to_timestamp("incidents", "created_at")
    _to_timestamp("incidents", "resolved_at", nullable=True)

    # users
    _to_timestamp("users", "created_at")
